import Config from 'react-native-config';

const pureRelay = tpyrc => tpyrc;

const ENV=pureRelay(Config.ENV);
const REACT_NATIVE_APP_APPID=pureRelay(Config.REACT_NATIVE_APP_APPID);
const REACT_NATIVE_APP_API_KEY=pureRelay(Config.REACT_NATIVE_APP_API_KEY);
const REACT_NATIVE_APP_CLIENTID=pureRelay(Config.REACT_NATIVE_APP_CLIENTID);
const REACT_NATIVE_APP_PROJECT_ID=pureRelay(Config.REACT_NATIVE_APP_PROJECT_ID);
const REACT_NATIVE_APP_AUTH_DOMAIN=pureRelay(Config.REACT_NATIVE_APP_AUTH_DOMAIN);
const REACT_NATIVE_APP_DATABASE_URL=pureRelay(Config.REACT_NATIVE_APP_DATABASE_URL);
const REACT_NATIVE_APP_STORAGEBUCKET=pureRelay(Config.REACT_NATIVE_APP_STORAGEBUCKET);
const REACT_NATIVE_APP_MESSAGINGSENDERID=pureRelay(Config.REACT_NATIVE_APP_MESSAGINGSENDERID);
const REACT_NATIVE_APP_MEASUREMENT_ID=pureRelay(Config.REACT_NATIVE_APP_MEASUREMENT_ID);
const REACT_NATIVE_APP_PERSISTENCE=pureRelay(Config.REACT_NATIVE_APP_PERSISTENCE);

export default {
    ENV,
    REACT_NATIVE_APP_APPID,
    REACT_NATIVE_APP_API_KEY,
    REACT_NATIVE_APP_CLIENTID,
    REACT_NATIVE_APP_PROJECT_ID,
    REACT_NATIVE_APP_AUTH_DOMAIN,
    REACT_NATIVE_APP_DATABASE_URL,
    REACT_NATIVE_APP_STORAGEBUCKET,
    REACT_NATIVE_APP_MESSAGINGSENDERID,
    REACT_NATIVE_APP_MEASUREMENT_ID,
    REACT_NATIVE_APP_PERSISTENCE
};